#!/bin/sh
# Nightly runtime-DB backup on the VPS (DEPLOY.md Фаза 1 §5). Only game.db —
# game_static.db is regenerated by the offline pipeline, not backed up here.
# Installed via cron: 0 3 * * * /opt/teplee/backup.sh >> /opt/teplee/backup.log 2>&1
set -eu

DATA_DIR=/opt/teplee/data
BACKUP_DIR="$DATA_DIR/backup"
KEEP=7

mkdir -p "$BACKUP_DIR"
sqlite3 "$DATA_DIR/game.db" ".backup '$BACKUP_DIR/game-$(date +%F).db'"

# shellcheck disable=SC2012
ls -t "$BACKUP_DIR"/game-*.db 2>/dev/null | tail -n +$((KEEP + 1)) | xargs -r rm --
